In [12]:
##Qiuming Li
import os
import csv
import pandas as pd
root_path=r'C:\Users\49162\Desktop\python\images\camera'
img = os.listdir( root_path )
print(len(img))
train=pd.DataFrame(data=img)
train.to_csv(r'C:\Users\49162\Desktop\python/train1.csv',index=0,header=0)
##output: the number of images in file

500


In [ ]:
from PIL import Image
import numpy as np
import sys
import os
import csv

#create file list
def createFileList(myDir, format='.png'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList
# load the original image
myFileList = createFileList('C:/Users/49162/Desktop/python/camera')


for file in myFileList:
    print(file)
    img_file = Image.open(file)

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    img_grey = img_file.convert('L')
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("image_to_csv.csv", 'a') as f:
         writer = csv.writer(f)
         writer.writerow(value)

C:/Users/49162/Desktop/python/camera
C:/Users/49162/Desktop/python/camera\CameraImage_0001.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0002.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0003.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0004.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0005.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0006.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0007.png


C:\Users\49162\AppData\Local\Temp/ipykernel_17096/638227978.py:31: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))


[182 182 182 ... 182 183 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0008.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0009.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0010.png
[182 182 182 ... 182 183 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0011.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0012.png
[182 182 182 ... 182 183 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0013.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0014.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0015.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0016.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0017.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0018.png
[182 182 182 ... 182 182 181]
C:

[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0102.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0103.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0104.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0105.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0106.png
[182 182 182 ... 182 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0107.png
[182 182 182 ... 182 183 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0108.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0109.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0110.png
[182 182 182 ... 182 183 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0111.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0112.png
[182 182 182 ... 182 183 182]
C:

[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0202.png
[182 182 182 ... 181 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0203.png
[182 182 182 ... 181 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0204.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0205.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0206.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0207.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0208.png
[182 182 182 ... 181 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0209.png
[182 182 182 ... 181 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0210.png
[182 182 182 ... 182 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0211.png
[182 182 182 ... 181 182 181]
C:/Users/49162/Desktop/python/camera\CameraImage_0212.png
[182 182 182 ... 182 182 181]
C:

C:/Users/49162/Desktop/python/camera\CameraImage_0297.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0298.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0299.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0300.png
[181 182 182 ... 183 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0301.png
[181 182 182 ... 183 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0302.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0303.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0304.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0305.png
[181 182 182 ... 183 182 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0306.png
[181 182 182 ... 183 181 182]
C:/Users/49162/Desktop/python/camera\CameraImage_0307.png
[181 182 182 ... 183 182 182]
C:/Users/49162/Desktop/python/ca